version: '3.4'

services:
  db:
    build:
      context: devOps/db
      dockerfile: Dockerfile
      target: base
    image: postgres:9.6
    restart: always
    ports:
      - ${DB_PORT}:5432
    networks:
      backend:
        ipv4_address: ${EM_DOCKER_DATABASE_IP}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./devOps/db/config/postgresql.conf:/etc/postgresql.conf
      - ./devOps/db/sql:/docker-entrypoint-initdb.d/
      - ./devOps/db/logs:/logs
    command: >
      postgres -c config_file=/etc/postgresql.conf
      -c logging_collector=on -c log_destination=stderr -c log_directory=/logs

  redis:
    build:
      context: devOps/redis
      dockerfile: Dockerfile
      target: base
    image: 'bitnami/redis:4.0.13'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${REDIS_PORT}:6379
    networks:
      backend:
        ipv4_address: ${EM_DOCKER_REDIS_IP}
    volumes:
      - redis-persistence:/bitnami/redis/data

volumes:
  postgres-data:
  app:
  redis-persistence:

networks:
  backend:
    ipam:
      config:
        - subnet: ${EM_DOCKER_BACKEND_SUBNET}


