version: '3.4'

services:
  db:
    build:
      context: devOps/db
      dockerfile: Dockerfile
      target: base
    image: postgres:9.6
    restart: always
    ports:
      - ${DB_PORT}:5432
    networks:
      backend:
        ipv4_address: ${EM_DOCKER_DATABASE_IP}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./devOps/db/config/postgresql.conf:/etc/postgresql.conf
      - ./devOps/db/sql:/docker-entrypoint-initdb.d/
      - ./devOps/db/logs:/logs
    command: >
      postgres -c config_file=/etc/postgresql.conf
      -c logging_collector=on -c log_destination=stderr -c log_directory=/logs

  java:
    build:
      context: devOps/java
      dockerfile: Dockerfile
      target: base
    image: maven:3.5-jdk-8
    ports:
      - ${PORT_APPLICATION}:8080
    networks:
      backend:
        ipv4_address: ${EM_DOCKER_JAVA_IP}
    volumes:
      - $HOME/.m2:/root/.m2
      - ./:/app
    working_dir: /app
    depends_on:
      - db
    command: >
      /bin/bash -c "
          mvn install
          sleep 60;
          java -jar ./order-service/target/com-order-service-1.0.jar
        echo Connected!;
      "


  redis:
    build:
      context: devOps/redis
      dockerfile: Dockerfile
      target: base
    image: 'bitnami/redis:4.0.13'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - ${REDIS_PORT}:6379
    networks:
      backend:
        ipv4_address: ${EM_DOCKER_REDIS_IP}
    volumes:
      - redis-persistence:/bitnami/redis/data

volumes:
  postgres-data:
  app:
  redis-persistence:
  maven-repository:

networks:
  backend:
    ipam:
      config:
        - subnet: ${EM_DOCKER_BACKEND_SUBNET}


